### PR TITLE
Delete/archive the entire Burn-to-Redeem doc

### PR DESCRIPTION
**Pull request by isaaczaak**
Delete the entire B2R doc

### CODE REVIEW

**Comment by isaaczaak** [comment]
@iainnash is there a way for us to archive this doc vs deleting it entirely? 

i think it's worth keeping a copy of this in case we want to reintroduce this feature in the future.

**Comment by isaaczaak** [comment]
confirmed by @iainnash that it's ok to completely delete this.

**Review by oveddan — APPROVED** [review]

**Comment by IsabellaSmallcombe** [comment]
I think we need to remove the link for the b2r docs in the sidebar as well @isaaczaak

**Review by IsabellaSmallcombe — CHANGES_REQUESTED** [review]
have to fix the vercel build before deploying this

**Review by IsabellaSmallcombe — APPROVED** [review]

**Pull request merged**
